import { writeFileSync, existsSync } from 'fs';
import { findEnvFile } from '../utils/env';

export function handleSetup(subArgs: string[]): void {
  const modelIdx = subArgs.indexOf('--model');
  const chosenModel = modelIdx !== -1 ? subArgs[modelIdx + 1] : null;
  const force = subArgs.includes('--force');

  const envFile = findEnvFile();
  console.log('Ordewell Setup');
  console.log('──────────────\n');

  if (existsSync(envFile) && !force) {
    console.log(`Found existing .env at ${envFile}`);
    console.log('Use --force to overwrite.');
    process.exit(0);
  }

  let content = `# Ordewell configuration
# Generated by: ordewell setup

`;

  if (chosenModel) {
    content += `ORCHESTRATOR_MODEL=${chosenModel}\n`;
  }

  const apiKey = process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY;
  const geminiKey = process.env.GEMINI_API_KEY;

  if (apiKey) {
    content += `OPENROUTER_API_KEY=${apiKey}\n`;
  } else if (geminiKey) {
    content += `GEMINI_API_KEY=${geminiKey}\n`;
  } else {
    content += `# OPENROUTER_API_KEY=sk-or-your-key-here\n# GEMINI_API_KEY=your-key-here\n`;
  }

  content += `
# Default models (uncomment to change)
# ORCHESTRATOR_MODEL=deepseek/deepseek-v4-flash
# OPENROUTER_BASE_URL=https://openrouter.ai/api/v1

# Use a custom OpenAI-compatible endpoint
# OPENAI_COMPATIBLE_BASE_URL=http://localhost:11434/v1
# OPENAI_COMPATIBLE_API_KEY=your-key-here

# Or plan with a coding agent you already have installed — no API key needed,
# it uses that agent's own subscription. Set the model to one of its own.
# AI_PROVIDER=claude-code|codex|opencode
# ORCHESTRATOR_MODEL=haiku
# ORDEWELL_PLANNER_EFFORT=low

# Or pick a named provider preset via AI_PROVIDER:
# AI_PROVIDER=openai|anthropic|mistral|xai|groq|deepseek|together|fireworks|perplexity|cerebras|deepinfra|cohere|novita|zhipu|kimi|doubao|qwen|hunyuan|baichuan|minimax|yi|stepfun|siliconflow
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-...
# MISTRAL_API_KEY=...
# TOGETHER_API_KEY=...
# FIREWORKS_API_KEY=...
# PERPLEXITY_API_KEY=...
# CEREBRAS_API_KEY=...
# DEEPINFRA_API_KEY=...
# COHERE_API_KEY=...
# NOVITA_API_KEY=...
# ZHIPU_API_KEY=...
# MOONSHOT_API_KEY=...
# ARK_API_KEY=...
# DASHSCOPE_API_KEY=...
# HUNYUAN_API_KEY=...
# BAICHUAN_API_KEY=...
# MINIMAX_API_KEY=...
# YI_API_KEY=...
# STEPFUN_API_KEY=...
# SILICONFLOW_API_KEY=...
`;

  writeFileSync(envFile, content);
  console.log(`Wrote: ${envFile}`);
  console.log('Review and edit the file, then run: ordewell tui');
}
